spec:
  template:
    spec:
      containers:
        - image: docker/light-proxy
          env:
            - name: sample-env-for-light-proxy
              value: sample-value
        - image: client-service
          env:
            - name: "DB_HOST"
              value: "localhost"
            - name: DB_PORT
              value: "9090"
            - name: JUST_AN_ENV
              value: "justAnEnvValue"
            - name: SECRET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sampleSealedSecretNamespace
                  key: nameKeyOfSecret
            - name: ENV_SECRET_ONLY_IN_YAML
              valueFrom:
                secretKeyRef:
                  name: envSecretValue
                  key: nameKeyOfSecretUnique